---
title: "&nbsp;"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---



```{r setup, include=FALSE}

library(gsheet)
library(tidyverse)
library(crosstalk)
library(DT)
library(ggthemes)
library(janitor)
library(cowplot)
library(plotly)

Sys.setlocale("LC_ALL", "pt_BR.UTF-8")


#mg_prod <- gsheet2tbl("https://docs.google.com/spreadsheets/d/13xAflAQ-x78Vkq0O0jUEkUxHPq5G1R4gwqzillMxoTo/edit?usp=sharing")



wb2<- gsheet2tbl("https://docs.google.com/spreadsheets/d/1R6UXFcsbVgpPYyvfkPvZ81rqkyk4U_9aS7qV8TKPsxQ/edit?usp=sharing")


wb_all <- wb2 %>%
  filter(labcode != 0) %>%
    mutate(id = case_when(
    is.na(py_binomial) ~ "No",
    TRUE ~ "Yes"
  )) %>%
  mutate(wheat = case_when(
    host_binomial == "Triticum aestivum" ~ "Wheat",
    TRUE ~ "Non-wheat"
  ))

wb_all <- wb_all %>% 
  dplyr::select(labcode, year, country, state_province, county_municipality, lat, lon, host_binomial, py_binomial,  py_lineage, wheat)

set.seed(1000)
wb_all$lat <- round(jitter(wb_all$lat, factor = 1, amount = 0.001), 4)
wb_all$lon <- round(jitter(wb_all$lon, factor = 1, amount = 0.001), 4)
sd <- SharedData$new(wb_all)
sd2 <- SharedData$new(wb_all)

```



### Strains by host

```{r echo=FALSE, layout="l-body-outset"}


p_host <- wb_all %>% 
  tabyl(host_binomial) %>% 
  ggplot(aes(reorder(host_binomial, n), n))+
  geom_col(fill = "#558796")+
  theme_minimal_grid()+
  coord_flip()+
  theme(legend.position = "none", 
        #plot.margin = margin(1, 2, 2, 2, "cm"), 
        axis.text.y = element_text(face = "italic"))+
  labs(x = "", y = "Number of strains", title = "Host species")
  
p_host
  
  

```


### Strains by species

```{r echo=FALSE, layout="l-body-outset"}
library(janitor)

p_py <- wb_all %>% 
  filter(py_binomial != "NA") %>% 
  tabyl(py_binomial) %>% 
    ggplot(aes(reorder(py_binomial, n), n))+
geom_col(fill = "#558796")+
  theme_minimal_grid()+
  coord_flip()+
  theme(legend.position = "none", plot.margin = margin(2, 2, 2, 2, "cm"), axis.text.y = element_text(face = "italic"))+
  labs(x = "", y = "Number of strains", title = "Pyricularia spp.")
  
p_py
  
  


```

### Strains by lineages


```{r echo=FALSE, layout="l-body-outset"}
library(janitor)

p_lin <- wb_all %>% 
  filter(py_lineage != "NA") %>% 
  tabyl(py_lineage) %>% 
    ggplot(aes(reorder(py_lineage, n), n))+
  geom_col(fill = "#558796")+
  theme_minimal_grid()+
  coord_flip()+
  theme(legend.position = "none", plot.margin = margin(2, 2, 2, 2, "cm"))+
  labs(x = "", y = "Number of strains", title = "P. oryzae lineages")
  
p_lin
  
  


```




