---
title: "&nbsp;"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---


```{r setup, include=FALSE}
library(gsheet)
library(tidyverse)
library(crosstalk)
library(DT)
library(ggthemes)
library(janitor)
library(cowplot)
library(plotly)
library(flexdashboard)
library(tidyverse)
library(crosstalk)
library(plotly)
library(viridis)
library(leaflet.providers)
library(leaflet)

Sys.setlocale("LC_ALL", "pt_BR.UTF-8")



#DelPonte Lab
delponte = gsheet2tbl("https://docs.google.com/spreadsheets/d/1R6UXFcsbVgpPYyvfkPvZ81rqkyk4U_9aS7qV8TKPsxQ/edit?usp=sharing")
delponte_all <- delponte %>%
  filter(labcode != 0) %>%
    mutate(id = case_when(
    is.na(py_binomial) ~ "No",
    TRUE ~ "Yes"
  )) %>%
  mutate(wheat = case_when(
    host_binomial == "Triticum aestivum" ~ "Wheat",
    TRUE ~ "Non-wheat"
  )) %>% 
  mutate(lab = "DelPonte-Lab")

delponte_all = delponte_all %>% 
  dplyr::select(lab, labcode, year, lat, lon, country, state_province, county_municipality, collector, host_binomial, py_binomial, py_lineage, wheat)


#Kamoun lab
kamoun = gsheet2tbl("https://docs.google.com/spreadsheets/d/13PyoQobtdE3xessW14rHud45MlXUOsMOgKDWG81kxCc/edit#gid=1082341206")
kamoun_all = kamoun %>%
  filter(labcode != 0) %>%
    mutate(id = case_when(
    is.na(py_binomial) ~ "No",
    TRUE ~ "Yes"
  )) %>%
  mutate(wheat = case_when(
    host_binomial == "Triticum aestivum" ~ "Wheat",
    TRUE ~ "Non-wheat"
  )) %>% 
  mutate(lab = "Kamoun-Lab")

kamoun_all <- kamoun_all %>% 
  dplyr::select(lab, labcode, year, lat, lon, country, state_province, county_municipality, collector, host_binomial, py_binomial, py_lineage, wheat)


#Raw data
wb_all = bind_rows(delponte_all, kamoun_all)


sd <- SharedData$new(wb_all)
sd2 <- SharedData$new(wb_all)

```


```{r echo=FALSE}
bscols(

filter_select("lab", "Work team", sd, ~ lab),
filter_select("year", "Year", sd, ~ year),
filter_select("host", "Origin host", sd, ~ host_binomial),
filter_select("py_species", "Pyricularia spp.", sd, ~ py_binomial),
filter_select("py_lineage", "P. oryzae lineage", sd, ~ py_lineage)

)
```


```{r echo=FALSE, layout="l-screen-inset shaded", fig.height=5}
library(crosstalk)


library(RColorBrewer)
library(htmltools)
pal <- colorFactor("Set2", domain = c("Wheat", "Non-wheat"))

leaflet(data = sd, width = "100%") %>%
 setView(-46.8, -20.40, zoom = 4) %>%
  addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  addProviderTiles("OpenTopoMap", group = "Terrain") %>%
  addScaleBar("bottomright") %>%
  addProviderTiles(providers$CartoDB.Voyager, group = "Default") %>%
  addLayersControl(
    baseGroups = c("Default", "Aerial", "Terrain"),
    overlayGroups = "Blast pathogen",
    options = layersControlOptions(collapsed = T)
  ) %>%
  addCircleMarkers(
  
    group = "wheat",
    radius = 6,
    fillOpacity = 1,
    weight = 0.5,
    label = paste(wb_all$host, "- Details"),
    fillColor = ~ pal(wheat),

    popup = paste(
      "<h3>Isolate details</h3>",
      "Work team:", wb_all$"lab", "<br>",
      "Code:", wb_all$"labcode", "<br>",
      "Host:", wb_all$"host_binomial", "</i>", "<br>",
       "City:", wb_all$"county_municipality", "<br>",
      "Year:", wb_all$"year", "<br>",
      "Species:<i>", wb_all$"py_binomial", "<br></i>",
        "Lineage:<i>", wb_all$"py_lineage", "<br></i>",
      "Collector:", wb_all$"collector", "<br>"
    )
  ) %>%
  addLegend("bottomleft",
    pal = pal,
    values = ~wheat,
    title = "Host",
    opacity = 1
  ) %>% 
  
  addMeasure(
    position = "bottomleft",
    primaryLengthUnit = "meters",
    primaryAreaUnit = "sqmeters",
    activeColor = "#3D535D",
    completedColor = "#7D4479") %>% 
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Level 3",
    onClick=JS("function(btn, map){ map.setZoom(3); }")))



```




